- title: "Consulting"
  description: "Strategic guidance for early-stage GTM execution."
  link: "https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ3peNMQiog0EdHevCPROsXg7xqzsq2EystZeOzhHz0Gugxu091eOjGaCFyt09dZjxgQu6dSut3o"
- title: "Hands-on Execution"
  description: "Direct implementation & tool integration."
  link: "https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ3peNMQiog0EdHevCPROsXg7xqzsq2EystZeOzhHz0Gugxu091eOjGaCFyt09dZjxgQu6dSut3o"
- title: "AI Training"
  description: "Custom workshops for marketing teams."
  link: "https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ3peNMQiog0EdHevCPROsXg7xqzsq2EystZeOzhHz0Gugxu091eOjGaCFyt09dZjxgQu6dSut3o"
- title: "Research & Analysis"
  description: "Market research & competitive analysis."
  link: "/ai-agents-training"
- title: "Get more out of your current revOps stack"
  description: "Leverage your existing tools for better insights."
  link: "https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ3peNMQiog0EdHevCPROsXg7xqzsq2EystZeOzhHz0Gugxu091eOjGaCFyt09dZjxgQu6dSut3o"
