name: Content Linter

on:
  push:
    paths:
      - "_posts/**/*.markdown"
  pull_request:
    paths:
      - "_posts/**/*.markdown"

jobs:
  content-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests pyspellchecker textstat

      - name: Run Content Linter
        run: python .github/scripts/content_linter.py